### ISSUE TITLE
preparation for addition to MultiAssayExperiment

### ISSUE THREAD

**Issue by lwaldron** [schifferl/MultiAssayExperiment#1]
Looking good Lucas! When these are fully-working, I suggest the following for incorporation into MultiAssayExperiment:

- take out the lines that install Bioconductor
- set default chunk option to eval=FALSE (unless there is some other way to make it an unevaluated vignette?). These will be too intensive to actually evaluate during package build, but they will be nice examples for people to try out.
- create a pull request to add to MultiAssayExperiment

**Comment by schifferl** [comment]
a pull request has been submitted to the master repo
